### ISSUE TITLE
It does not work - Class 'QAutocomplete_SourceEvent' not found

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_datatables#5]
![screen shot 2015-08-02 at 18 15 52](https://cloud.githubusercontent.com/assets/2853034/9026726/ffc329a6-3942-11e5-8cc8-492c22b92114.png)

**Comment by spekary** [comment]
Update the framework. There was a bug fixed there corresponding to this.

**Comment by kukrik** [comment]
This topic may be closed!
