### ISSUE TITLE
DataTables first attempt

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_datatables#6]
if I understand correctly, that this work is incomplete? Here does not work with the filter, sort and pagination. 

Whether I am here lost or I misunderstood :) ?

**Comment by spekary** [comment]
OK, try again. The problem was using Ajax with static data.

The ajax version doesn't do filtering (YET), but sorting and pagination should work.

**Comment by spekary** [comment]
Actually, just fixed the filtering too, so it should all be working. Be sure to pull the latest beta3 from framework. It will be needed too.
